// Constantes movidas para um ficheiro separado para limpar os componentes

export const ATIVIDADES_INDUSTRIAIS = [
    "ABATEDOURO - INDUSTRIALIZAÇÃO",
    "ABRASIVOS - ARTIGOS - FÁBRICA",
    "ACETILENO - FABRICA",
    "ACIDO EM GERAL - FABRICAS",
    "AÇUCAR - REFINARIAS - SEM CO-GERAÇÃO",
    "AÇUCAR - REFINARIAS COM CO-GERAÇÃO",
    "AÇUCAR - USINAS OU ENGENHOS SEM DESTILAÇÃO DE ALCOOL",
    "ADEREÇOS - OFICINA",
    "ADUBOS E FERTILIZANTES - FÁBRICA - ORIGEM ANIMAL OU VEGETAL",
    "ADUBOS E FERTILIZANTES - FÁBRICA - ORIGEM MINERAL",
    "AGUAS MINERAIS/GASOSAS, EXTRAÇÃO - ENGARRAFAMENTO",
    "ALCATRAO MINERAL - FABRICAS",
    "ALCATRAO VEGETAL - EXTRACAO E PREPARAÇÃO",
    "ALCOOL, USINA E DESTILARIA",
    "ALGODÃO - ABRIDORES, BATEDORES E PROCESSOS SEMELHANTES",
    "ALGODÃO - DESCASCADOR, DESCAROÇADOR",
    "ALGODÃO - FIAÇÃO",
    "ALGODÃO -TECELAGEM",
    "ALIMENTO PARA ANIMAIS - FÁBRICA",
    "ANIL - FÁBRICA",
    "ANÚNCIO - VIDE MATERIAL EMPREGADO",
    "ANUNCIOS LUMINOSOS E LETREIROS - FÁBRICA",
    "ARMAS E MUNIÇÕES - FÁBRICA - MATERIAL BELICO",
    "ARROZ - ENGENHO",
    "ASFALTO - USINA",
    "AUTOMOVEIS, CAMINHÕES, TRATORES E MOTOS - MONTADORAS",
    "AVEIA E FLOCOS - FÁBRICA",
    "AVIÁRIOS - (AVES E OVOS) COM QUALQUER TIPO DE AQUECIMENTO",
    "BALA COMESTIVEL - FÁBRICA",
    "BEBIDAS DESTILADAS - FÁBRICA",
    "BICICLETAS - FÁBRICA",
    "BIJUTERIAS - FÁBRICA",
    "BILHARES E BOLICHES - FABRICA",
    "BISCOITO OU BOLACHAS - FÁBRICA",
    "BOLSAS, CINTOS E CONGENERES - FÁBRICA (QUALQUER MATERIAL)",
    "BORDADO - OFICINA OU FÁBRICA",
    "BORRACHA - PREPARACAO E FABRICA DE ARTIGOS COM EMPREGO DE INFLAMAVEL",
    "BORRACHA - PREPARACAO E FÁBRICA DE ARTIGOS SEM EMPREGO DE INFLAMAVEL",
    "BOTÃO - FÁBRICA - QUALQUE TIPO DE MATERIAL",
    "BOTES - FÁBRICA",
    "BRINQUEDOS - FÁBRICA",
    "CACAU - USINA OU FÁBRICA A VAPOR",
    "CACAU - USINA OU FABRICA - A FOGO DIRETO OU A FRIO",
    "CAFÉ - BENEFICIAMENTO OU ENGENHO",
    "CAFÉ - TORREFAÇÃO E MOAGEM",
    "CAFÉ SOLUVEL",
    "CALCADOS - FÁBRICA E OFICINAS",
    "CANETAS E LAPISEIRAS - FÁBRICA",
    "CARAMELO - FÁBRICA",
    "CARBURETO DE CALCIO - FÁBRICA",
    "CARIMBOS - FÁBRICA E OFICINAS",
    "CARTUCHOS, FITAS PARA IMPRESSÃO - FÁBRICA",
    "CARVÃO ANIMAL - FÁBRICA",
    "CARVÃO MINERAL - FABRICAS",
    "CASTANHA DO PARA - USINAS DE BENEFICIAMENTO",
    "CELULOSE - FÁBRICA",
    "CERA ANIMAL E VEGETAL - BENEFICIAMENTO E PREPARO A ELETRECIDADE OU A VAPOR",
    "CERA ANIMAL E VEGETAL - BENEFICIAMENTO E PREPARO A FOGO DIRETO",
    "CERA ANIMAL E VEGETAL - BENEFICIAMENTO E PREPARO A FRIO",
    "CERAMICA, ARTIGO - FÁBRICA",
    "CEREAIS - PREPARO, EXTRAÇÃO ÓLEO, PELETIZAÇÃO, FARELO E MOAGEM",
    "CERVEJA E REFRIGERANTES - FÁBRICA",
    "CHAPEUS - SOL/ CHUVA / BENGALA - FABRICA",
    "CHARQUE",
    "CHARUTO - FÁBRICA",
    "CHOCOLATE / DOCES/ SORVETES/ BALAS/ CARAMELOS - FÁBRICA A VAPOR",
    "CHOCOLATE / DOCES/ SORVETES/ BALAS/ CARAMELOS - FABRICAS A FOGO DIRETO",
    "CIGARROS - FÁBRICA",
    "CIMENTO - FÁBRICA DE ARTIGOS",
    "CIMENTO/GESSO - FÁBRICA",
    "CINTA, COLETE E ESPARTILHO - VIDE ROUPA",
    "CINTO - FÁBRICA (QUALQUER MATERIAL)",
    "CIRURGICOS, HOSPITALARES E DENTARIOS - ARTIGOS - FÁBRICA",
    "COLA - FÁBRICA A FRIO",
    "COLA - FABRICA A QUENTE",
    "COLCHOES - FABRICA",
    "COMPUTADORES - FÁBRICA",
    "CONDIMENTO - COM OU SEM TORREFAÇÃO",
    "CONSERVAS ALIMENTICIAS - FÁBRICA",
    "CORDOARIAS - FABRICAS",
    "CORREARIAS - FABRICAS",
    "CORTICA - FABRICAS",
    "COSMETICOS - FÁBRICA - COM INFLAMÁVEIS",
    "COSMETICOS - FÁBRICA - SEM INFLAMÁVEIS",
    "COUROS E PELES, ARTIGOS - FABRICA",
    "COZINHA INDUSTRIAL (BUFFET, MARMITEX, SEM RESTAURANTE)",
    "CRINAS E CERDAS ANIMAIS - FABRICAS",
    "CRISTAL - FÁBRICA",
    "CURTUME",
    "CUTELARIA",
    "DENTÁRIO - APARELHOS E ARTIGOS - FÁBRICA",
    "DISCOS E CDS - FÁBRICA",
    "ELETRICIDADE - ARTIGOS - FÁBRICA",
    "ELETRICIDADE - ESTACOES E SUBESTAÇÕES TRANSFORMADORAS",
    "ELETRICIDADE - TORRE DE TRANSMISSÃO E DISTRIBUIÇÃO",
    "ELETRICIDADE - TRANSFORMADORES AO AR LIVRE",
    "ELETRICIDADE - USINA PLACAS SOLARES E OUTROS TIPOS",
    "ELETRICIDADE - USINAS HIDROELETRICAS (UHE OU PCH)",
    "ELETRICIDADE - USINAS TERMOELÉTRICAS",
    "ELETROELETRONICOS E ELETRODOMESTICOS - FÁBRICA",
    "ERVA - MATE - ENGENHOS",
    "ERVANARIAS, CASCAS E PLANTAS - PROCESSAMENTO/BENEFICIAMENTO",
    "ESMERIS - FÁBRICA",
    "ESPUMA, ARTIGOS - FABRICA",
    "ESTALEIROS",
    "ESTOPA - FABRICA",
    "EXPLOSIVOS - FABRICAS",
    "FÁBRICA EM DESMONTAGEM SEM MERCADORIAS",
    "FÁBRICA EM MONTAGEM SEM MERCDORIAS",
    "FABRICA PARADA COM MERCADORIA - VIDE TIPO DE MERCADORIA",
    "FÁBRICA PARADA OU DESOCUPADA - SEM MERCADORIA",
    "FARINHAS E FARELOS - BENEFICAMENTO E MOAGEM",
    "FARMACEUTICO, PRODUTOS - FABRICA A FRIO COM INFLAMAVEL",
    "FARMACEUTICO, PRODUTOS - FÁBRICA A FRIO SEM INFLAMAVEL",
    "FARMACEUTICO, PRODUTOS - FABRICA A QUENTE COM INFLAMAVEL",
    "FARMACEUTICO, PRODUTOS - FÁBRICA A QUENTE SEM INFLAMAVEL",
    "FAZENDA OU ESTABELECIMENTO RURAL - COM DEFENSIVOS AGRICOLAS",
    "FAZENDA OU ESTABELECIMENTO RURAL - SEM DEFENSIVOS AGRICOLAS",
    "FAZENDAS, COLCHAS, TOALHAS E EDREDONS - FÁBRICA",
    "FIBRA ANIMAL - FIAÇÃO/PROCESSOS PREVIOS",
    "FIBRA ANIMAL - TECELAGEM",
    "FIBRA ARTIFICIAL / SINTETICA - FILAMENTO",
    "FIBRA ARTIFICIAL / SINTETICA - TECELAGEM",
    "FIBRA VEGETAL - BENEFICAMENTO / PROCESSOS",
    "FITAS (TECIDO) - FABRICA",
    "FLORES / PLANTAS - VIVEIRO",
    "FLORES ARTIFICIAIS - FÁBRICA",
    "FOGOS DE ARTIFICIO - FABRICAS,",
    "FORRAGENS E RAÇÕES - FÁBRICA COM MOINHO",
    "FOSFOROS - FABRICA",
    "FRUTAS, HORTI FRUTI - BENEFICIAMENTO EMBALAGEM",
    "FUMO - PREPARAÇÃO E BENEFICIAMENTO",
    "FUNEBRES, ARTIGOS - FABRICA",
    "GAS CARBONICO - FÁBRICA",
    "GASES COMBUSTIVEIS - FABRICA E ENGARRAFAMENTO",
    "GELO - FÁBRICA",
    "GESSO, ARTIGO - FÁBRICA",
    "GRAFICA COM SISTEMAS DE TI",
    "GRAFICA CONVENCIONAL",
    "GRÃOS COMESTIVEL - BENEFICAMENTO E INDUSTRIALIZAÇÃO",
    "GUARDA CHUVA/SOL - FÁBRICA",
    "HIDROGENIO - FABRICA",
    "HOSPITALARES, APARELHOS - FÁBRICA",
    "JORNAIS E REVISTAS - OFICINAS COM ROTOGRAVURA",
    "JORNAIS E REVISTAS - OFICINAS DE IMPRESSÃO",
    "LACRE - FABRICAS",
    "LADRILHOS, PISOS E AZULEJOS - FÁBRICA",
    "LAPIS - FÁBRICA",
    "LATICINIOS, LEITE - FÁBRICA E USINAS",
    "LETREIRO - VIDE MATERIAL EMPREGADO",
    "LINHAS PARA COSER",
    "LIVROS - FÁBRICA E ENCARDENADORA",
    "LIXA - FÁBRICA",
    "LONA - ARTIGOS - FÁBRICA",
    "LOUÇAS, CERÂMICAS E PORCELANAS - FÁBRICA",
    "MADEIRA - ESTUFAS PARA SECAGEM",
    "MADEIRA - FABRICA DE ARTEFATOS, CARPINTARIAS E MARCENARIAS",
    "MADEIRA - FABRICA DE ARTEFATOS, CARPINTARIAS E MARCENARIAS COM ESTOFAMENTO",
    "MALAS - VIDE MATERIAL EMPREGADO",
    "MASSAS ALIMENTICIAS - FÁBRICA",
    "MATADOUROS - (INDUSTRIALIZAÇÃO)",
    "MEIAS - FÁBRICA",
    "METAL - ARTIGOS - FÁBRICA COM PROCESSOS A QUENTE",
    "METAL - ARTIGOS - FÁBRICA SEM PROCESSOS A QUENTE",
    "METAL - FUNDIÇÕES DE METAL FERROSO E OUTROS",
    "METAL - NÃO FERROSO, ARTIGOS - FÁBRICA",
    "METAL - TRATAMENTO TERMO QUIMICO",
    "MINERAÇÃO",
    "MOINHO - MOAGEM E SILO",
    "MOLDURA - FÁBRICA",
    "MOVEIS - FABRICA (VIDE MATERIA -PRIMA)",
    "MOVEIS - FABRICA DE MADEIRA COM ESTOFAMENTO",
    "MOVEIS - FABRICA DE MADEIRA SEM ESTOFAMENTO",
    "MUSICA - FABRICA DE INSTRUMENTOS DE MADEIRA",
    "MUSICA - FÁBRICA DE INSTRUMENTOS DE METAL",
    "MUSICA - FÁBRICA DE INSTRUMENTOS DE QUALQUER MATERIAL (EXCETO MADEIRA)",
    "OLARIAS",
    "OLEADOS - FABRICA",
    "OLEOS MINERAIS / LUBRIFICANTES - FABRICA",
    "OLEOS VEGETAIS E SEMENTES OLEAGINOSAS - FÁBRICA",
    "ORTOPEDICOS, APARELHOS - FÁBRICA",
    "OSSOS, CHIFRES E SIMILARES - ARTIGOS - FÁBRICA",
    "OURIVES",
    "OXIGENIO - FÁBRICA",
    "PALITOS",
    "PANIFICAÇÃO - FÁBRICA",
    "PAPEL - APARAS/SUCATA",
    "PAPEL - CELULOSE - FÁBRICA",
    "PAPEL/PAPELÃO - FÁBRICA",
    "PAPEL/PAPELÃO - FÁBRICA DE ARTIGOS",
    "PAPEL/PAPELÃO - FABRICA DE ARTIGOS - PROC IMPERMEABILZAÇÃO E ROTOGRAVURA",
    "PAPEL/PAPELÃO - FÁBRICA DE ARTIGOS C PROCESSOS DE IMPERMEABILIZAÇÃO E INFLAMÁVEIS",
    "PEDRAS PRECIOSAS E SEMI PRECIOSAS - LAPIDAÇÃO",
    "PEIXES - FÁBRICA DE CONSERVAS DE PEIXES OU SALGA",
    "PERFUMARIAS - FABRICAS - COM INFLAMÁVEIS",
    "PERFUMARIAS - FABRICAS -SEM INFLAMÁVEIS",
    "PINTURAS - OFICINAS",
    "PIRETRO (FLOR DE)",
    "PIRO LENHOSO (ALCOOL DE MADEIRA) - FABRICA",
    "PLASTICO - MATERIA - FABRICA",
    "PLASTICO, ARTIGO - FABRICA COM RECICLAGEM",
    "PLASTICO, ARTIGO - FÁBRICA SEM INFLAMAVEIS",
    "PLASTICO, ARTIGOS - FÁBRICA COM INFLAMAVEIS",
    "PLASTICO, EMBALAGEM - FÁBRICA COM INFLAMAVEIS",
    "PLASTICO, EMBALAGEM - FÁBRICA SEM INFLAMAVEIS",
    "PLUMAS - FABRICAS",
    "PNEU E CAMARAS DE AR - FÁBRICA, COM RECAUCHUTAGEM",
    "PNEU E CAMARAS DE AR - FABRICA, SEM RECAUCHUTAGEM",
    "PÓ DE PEDRA - FÁBRICA",
    "PRODUTOS ALIMENTICIOS - ORIGEM ANIMAL",
    "PRODUTOS ALIMENTICIOS - ORIGEM VEGETAL",
    "PRODUTOS QUIMICOS - FÁBRICA SEM INFLAMAVEL",
    "PRODUTOS QUIMICOS - FABRICAS COM INFLAMAVEL",
    "RAÇÃO - FÁBRICA",
    "RELOGIO - FÁBRICA",
    "RENDAS - FÁBRICA",
    "ROUPAS - FÁBRICA E OFICINA",
    "ROUPAS - FÁBRICA, OFICINA E TINTURARIA",
    "SABÃO - FABRICA",
    "SABONETE - FABRICA",
    "SAL - EXTRAÇÃO E BENEFICIAMENTO",
    "SAPONACEO - FABRICA",
    "SERRARIA",
    "SIDERURGICA",
    "SORVETE - FÁBRICA",
    "TAPETES - FÁBRICA FIBRAS ANIMAIS, ARTIFICIAIS E SINTETICAS",
    "TAPETES - FABRICAS FIBRA VEGETAL",
    "TELEFONES, TELEGRAFOS E CELULARES - FÁBRICA APARELHOS E ACESSORIOS",
    "TEMPEROS - PREPARAÇÃO E EMBALAGEM",
    "TINTAS E VERNIZES - FÁBRICA SEM INFLAMAVEIS",
    "TINTAS E VERNIZES - FABRICAS Á BASE DE INFLAMAVEIS",
    "TIPOGRAFIAS",
    "TOUCADOR, ARTIGO - FÁBRICA",
    "USINA DE CONCRETO",
    "VELA - FABRICA",
    "VIDROS - FÁBRICA",
    "VIDROS, ARTIGO - FÁBRICA",
    "VIME - JUNCO - PIAÇABA E SIMILARES - FABRICAS",
    "VINAGRE - FÁBRICA",
    "VINHOS - FÁBRICA COM OU SEM ENGARRAFAMENTO",
];

export const ATIVIDADES_COMERCIAIS = [
  "ABRASIVOS - DEPÓSITO",
  "ABRASIVOS - LOJA",
  "ACADEMIAS",
  "ACETILENO - DEPOSITO COM MANIPULAÇÃO",
  "ACETILENO - DEPOSITO SEM MANIPULAÇÃO",
  "ACIDOS EM GERAL -DEPÓSITO",
  "ACIDOS EM GERAL -LOJA",
  "AÇOUGUE",
  "AÇUCAR OU MELAÇO - DEPOSITO",
  "ADEGA",
  "ADEREÇOS - DEPÓSITO",
  "ADEREÇOS - LOJA",
  "ADUBOS E FERTILIZANTES - DEPOSITO - COM DEFENSIVO AGRICOLA",
  "ADUBOS E FERTILIZANTES - DEPOSITO - SEM DEFENSIVO AGRICOLA",
  "ADUBOS E FERTILIZANTES - LOJA - COM DEFENSIVO AGRICOLA",
  "ADUBOS E FERTILIZANTES - LOJA - SEM DEFENSIVO AGRICOLA",
  "AEROPORTO - COM LOJAS E/OU RESTAURANTES",
  "AGENCIAS - CAMBIO E MOEDAS",
  "AGENCIAS - CORREIOS - COM MERCADORIAS",
  "AGENCIAS - CORREIOS - SEM MERCADORIAS",
  "AGROPECUARIOS, PRODUTOS - DEPÓSITO",
  "AGROPECUARIOS, PRODUTOS - LOJA",
  "AGUARRAS - DEPOSITO COM MANIPULAÇÃO",
  "AGUARRAS - DEPOSITO SEM MANIPULAÇÃO",
  "AGUAS MINERAIS/GASOSAS - LOJA E/OU DEPOSITO",
  "ALCOOL E BEBIDAS ALCOOLICAS - DEPÓSITO",
  "ALCOOL E BEBIDAS ALCOOLICAS - LOJA",
  "ALCOOL INDUSTRIAL - DEPOSITO COM MANIPULAÇÃO",
  "ALCOOL INDUSTRIAL - DEPOSITO SEM MANIPULAÇÃO",
  "ALFAIATARIA",
  "ALGODÃO - DEPOSITO EM FARDOS",
  "ALGODÃO - DEPOSITO EM FARDOS AO AR LIVRE",
  "ALGODÃO - DEPOSITOS DE PANO, FIO OU TECIDOS ACABADOS",
  "ALGODÃO - HIDROFILO - DEPOSITO DE PRODUTOS ACABADOS",
  "ALIMENTO, CONSERVAS - DEPÓSITO",
  "ALIMENTO, CONSERVAS - LOJA",
  "ANIMAIS - EXCLUSIVAMENTE LOJAS (PET SHOP)",
  "ANTIGUIDADES -LOJA E/OU DEPOSITO COM OU SEM OFICINA DE CONSERTO",
  "ANUNCIOS LUMINOSOS E LETREIROS - AFIXADO OU SOBRE EDIFICAÇÃO",
  "ANUNCIOS LUMINOSOS E LETREIROS - DEPÓSITO",
  "ANUNCIOS LUMINOSOS E LETREIROS - INSTALADOS AO AR LIVRE OU EM OUTROS LOCAIS PÚBLICOS",
  "ANUNCIOS LUMINOSOS E LETREIROS - LOJA",
  "ARMARINHOS - DEPÓSITO",
  "ARMARINHOS - LOJA",
  "ARMAS E MUNIÇÕES -DEPÓSITO",
  "ARMAS E MUNIÇÕES -LOJA",
  "ARMAZEM DE DEPOSITOS - MERCADORIAS EM CONTAINERS AO AR LIVRE",
  "ARMAZEM DE DEPOSITOS - MERCADORIAS INDISCRIMINADAS COM INFLAMAVEL",
  "ARMAZEM DE DEPOSITOS - MERCADORIAS INDISCRIMINADAS SEM INFLAMAVEL",
  "ARROZ - DEPOSITOS COM SECADORES",
  "ARROZ - DEPOSITOS SEM SECADORES",
  "ASFALTO - DEPOSITOS",
  "ASILOS E ORFANATOS",
  "ATELIER, ARTES - OFICINAS E EXPOSIÇÕES",
  "AUTO PEÇAS - DEPÓSITO",
  "AUTO PEÇAS - LOJA",
  "AUTOMOVEIS E MOTOS - CONCESSIONARIAS AUTORIZADAS",
  "AUTOMOVEIS E MOTOS - LOJAS, LOCADORAS OU DEPOSITOS",
  "AUTOMOVEIS E MOTOS - MECANICA, TROCA DE OLEO E FUNILARIA",
  "AUTOMOVEIS E MOTOS - TAPEÇARIA",
  "AUTOMOVEIS E MOTOS - VIDROS E SOM - INSTALAÇÃO",
  "AUTOMOVEL E MOTOS - AUTO ELETRICO",
  "AVES E OVOS - DEPÓSITO",
  "AVES E OVOS - LOJA",
  "AVIAMENTOS - DEPÓSITO",
  "AVIAMENTOS - LOJA",
  "BALAS, CARAMELOS, DOCES - DEPÓSITO",
  "BALAS, CARAMELOS, DOCES - LOJA",
  "BANCA DE JORNAIS E REVISTAS",
  "BANNER, CONFECÇÃO",
  "BAR, BOTEQUIM E PASTELARIAS",
  "BARBEARIA E CABELEIREIROS",
  "BARCOS - DEPÓSITO - EXCETO MARINAS",
  "BARCOS - LOJA - EXCETO MARINAS",
  "BAZAR",
  "BEBIDAS DISTRIBUIDORAS - DEPOSITO",
  "BIBLIOTECA",
  "BICICLETAS - DEPÓSITO",
  "BICICLETAS - LOJA",
  "BIJUTERIAS - DEPÓSITO",
  "BIJUTERIAS - LOJA",
  "BILHARES, BOLICHES E JOGOS ELETRONICOS - SALOES",
  "BINGOS - SALÃO",
  "BOATE",
  "BOLACHA/BISCOITO - DEPÓSITO",
  "BOLACHA/BISCOITO - LOJA",
  "BOLSA DE MERCADORIAS E VALORES",
  "BOLSAS, CINTOS E CONGENERES - DEPOSITO",
  "BOLSAS, CINTOS E CONGENERES - LOJA COM OU SEM OFICINA",
  "BOMBONIERE - DEPÓSITO",
  "BOMBONIERE - LOJA",
  "BONDES - LOCAL DE GUARDA OU DEPOSITO DE ACESSORIOS E OFICINAS",
  "BORRACHA - ARTIGOS - DEPÓSITO",
  "BORRACHA - ARTIGOS - LOJA",
  "BORRACHA CRUA - DEPÓSITO",
  "BORRACHA CRUA - LOJA",
  "BORRACHARIA",
  "BOTES - DEPÓSITO",
  "BOTES - LOJA",
  "BRECHO (BELCHIORES)",
  "BRINQUEDOS - DEPÓSITO",
  "BRINQUEDOS - LOJA",
  "BUFFET",
  "CABARES, SALOES PUBLICOS DE BAILES.",
  "CABELEIREIROS",
  "CACAU - DEPOSITOS",
  "CAFÉ - DEPOSITOS",
  "CAFETERIA",
  "CALÇADOS - DEPÓSITO",
  "CALÇADOS - LOJA",
  "CAMA, MESA E BANHO - ARTIGOS - DEPÓSITO",
  "CAMA, MESA E BANHO - ARTIGOS - LOJA",
  "CAMARAS MORTUARIAS",
  "CANTEIROS DE OBRA E/OU STAND DE VENDAS",
  "CARBURETO DE CALCIO - DEPOSITO",
  "CARIMBOS - DEPÓSITO",
  "CARIMBOS - LOJA",
  "CART, PISTA",
  "CARTORIOS",
  "CARVÃO - DEPÓSITO",
  "CARVÃO - LOJA",
  "CASA DE SHOWS, ESPETACULOS",
  "CASAS DE BANHO SAUNAS E TERMAS",
  "CASCAS DE ARVORES / PLANTAS - DEPÓSITO",
  "CASCAS DE ARVORES / PLANTAS - LOJA",
  "CASSINO",
  "CELULOSE - DEPOSITO",
  "CENTRO DE DISTRIBUIÇÃO DE PRODUTOS ALIMENTICIOS",
  "CENTRO DE DISTRIBUIÇÃO DE PRODUTOS ELETRO-ELETRONICOS",
  "CENTRO DE DISTRIBUIÇÃO DE PRODUTOS MOVEIS E COLCHOES",
  "CENTRO DE DISTRIBUIÇÃO DE PRODUTOS UTILIDADES, UTENSILIOS DOMESTICOS - EXCETO MOVEIS",
  "CEREAIS - DEPÓSITO",
  "CEREAIS - LOJA",
  "CHAPEUS - SOL/ CHUVA / BENGALA - DEPÓSITO",
  "CHAPEUS - SOL/ CHUVA / BENGALA - LOJA",
  "CHARQUE",
  "CHARUTARIA",
  "CHAVEIRO",
  "CHOCOLATES E/OU SORVETES - DEPÓSITO",
  "CHOCOLATES E/OU SORVETES - LOJA",
  "CIGARROS - DEPÓSITO",
  "CIGARROS - LOJA",
  "CIMENTO - DEPÓSITO",
  "CIMENTO - LOJA",
  "CIMENTO/GESSO - DEPÓSITO DE ARTIGOS",
  "CIMENTO/GESSO - LOJA DE ARTIGOS",
  "CINE/FOTO E SOM - DEPÓSITO",
  "CINE/FOTO E SOM - LOJA",
  "CINEMAS",
  "CINEMATOGRAFIA - ARTIGO - DEPÓSITO",
  "CINEMATOGRAFIA - ARTIGO - LOJA",
  "CINEMATOGRAFIA - ESTUDIOS",
  "CINTA, COLETE E ESPARTILHO - VIDE ROUPAS",
  "CIRCO",
  "CIRURGICOS, HOSPITALARES E DENTARIOS - ARTIGOS - DEPÓSITO",
  "CIRURGICOS, HOSPITALARES E DENTARIOS - ARTIGOS - LOJA",
  "CLUBES DESPORTIVOS, SOCIAIS E RECREATIVOS",
  "COCHEIRAS E ESTABULOS",
  "COLCHOES - DEPÓSITO",
  "COLCHOES - LOJA",
  "COMPUTADORES - DEPÓSITO",
  "COMPUTADORES - LOJA",
  "CONSERVAS ALIMENTICIAS - DEPÓSITO",
  "CONSERVAS ALIMENTICIAS - LOJA",
  "CONSULTORIO E CLINICA COM IMAGEM",
  "CONSULTORIO E CLINICA DE ESTETICA",
  "CONSULTORIOS - MEDICOS, DENTARIOS E VETERINÁRIOS",
  "CONVENTOS",
  "COPIADORA E ENCARDENADORAS",
  "CORDOARIAS - DEPÓSITO",
  "CORDOARIAS - LOJA",
  "CORREARIAS - DEPÓSITO",
  "CORREARIAS - LOJA",
  "CORTICA - DEPÓSITO",
  "CORTICA - LOJA",
  "COSMETICOS - DEPÓSITO",
  "COSMETICOS - LOJA",
  "COUROS E PELES - ARTIGOS -DEPÓSITO",
  "COUROS E PELES - ARTIGOS -LOJA",
  "CREMATORIO",
  "CRINAS E CERDAS ANIMAIS - DEPOSITOS E LOJAS, INCLUSIVE ARTIGOS",
  "CRISTAL, ARTIGOS - DEPÓSITO",
  "CRISTAL, ARTIGOS - LOJA",
  "DANCETERIA",
  "DELEGACIA",
  "DENTARIOS, ARTIGOS - DEPÓSITO",
  "DENTARIOS, ARTIGOS - LOJA",
  "DEPOSITOS PUBLICOS",
  "DISCOS E CDS - DEPÓSITO",
  "DISCOS E CDS - LOJA",
  "DIVERSOES ELETRONICAS",
  "DROGARIAS E FARMACIAS - COM MANIPULAÇAO",
  "DROGARIAS E FARMACIAS - SEM MANIPULAÇAO",
  "EDIFICIOS DESOCUPADOS",
  "EDIFICIOS EM CONSTRUÇÃO OU RECONSTRUÇÃO",
  "ELETRO -ELETRONICOS, APARELHOS - DEPÓSITO",
  "ELETRO -ELETRONICOS, APARELHOS - LOJA",
  "ELETRO-ELETRONICOS, OFICINA",
  "ELETRODOMESTICOS - DEPÓSITO",
  "ELETRODOMESTICOS - LOJA",
  "EMBALADORA DE PRODUTOS DIVERSOS",
  "EMPÓRIO",
  "EMPRESA DE LOGISTICA",
  "ENXOFRE - DEPOSITO",
  "ERVA MATE - DEPOSITO",
  "ERVANARIAS - DEPÓSITO",
  "ERVANARIAS - LOJA",
  "ESCOLAS, CRECHES, FACULDADES - PARTICULAR",
  "ESCOLAS, CRECHES, FACULDADES - PUBLICA",
  "ESCRITORIO DE TRANSMISSÃO ELETRÔNICA",
  "ESCRITÓRIOS",
  "ESPORTES - DEPÓSITO",
  "ESPORTES - LOJA",
  "ESTACIONAMENTO COM DEPOSITO OF INFLAMAVEIS",
  "ESTACIONAMENTO SEM DEPOSITO OF INFLAMAVEIS",
  "ESTACOES AEROVIARIAS, FERROVIARIAS, PORTUARIAS E RODOVIARIAS",
  "ESTAÇÕES DE TRATAMENTO DE AGUA E/OU ESGOTOS",
  "ESTACOES ELEVATORIAS E RESERVATORIAS DE AGUA",
  "ESTAMPARIA DE ROUPAS E TECIDOS",
  "ESTOFADOS/TAPEÇARIA - OFICINAS E DEPOSITOS",
  "ESTOPA - DEPOSITO",
  "ESTUDIO DE GRAVAÇÃO - IMAGEM",
  "ESTUDIO DE GRAVAÇÃO - SOM",
  "ESTUDIO FOTOGRAFICO",
  "EVENTOS/FEIRAS. SALÃO",
  "EXPLOSIVOS - DEPOSITOS",
  "EXPOSIÇÕES PERMANENTES E TEMPORARIAS, GALERIAS, FEIRAS E LEILOEIROS",
  "FARINHAS E FARELOS - DEPÓSITO",
  "FARINHAS E FARELOS - LOJA",
  "FARMÁCIA",
  "FAZENDAS, COLCHAS, TOALHAS E EDREDONS - DEPOSITOS",
  "FAZENDAS, COLCHAS, TOALHAS E EDREDONS - LOJAS",
  "FERRAGENS E FERRAMENTAS - DEPÓSITO",
  "FERRAGENS E FERRAMENTAS - LOJA",
  "FIBRAS - ARTIFICIAIS SINTETICAS - DEPÓSITO",
  "FIBRAS - ARTIFICIAIS SINTETICAS - LOJA",
  "FIBRAS - FIOS E PRODUTOS ACABADOS - DEPÓSITO",
  "FIBRAS - FIOS E PRODUTOS ACABADOS - LOJA",
  "FIBRAS - NATURAIS ANIMAIS (LA E SEDA) - DEPÓSITO",
  "FIBRAS - NATURAIS ANIMAIS (LA E SEDA) - LOJA",
  "FIBRAS - NATURAIS VEGETAIS (EXCETO ALGODAO) - DEPÓSITO",
  "FIBRAS - NATURAIS VEGETAIS (EXCETO ALGODAO) - LOJA",
  "FILATELIA",
  "FITAS/RENDAS/BORDADOS - DEPOSITO",
  "FITAS/RENDAS/BORDADOS - LOJAS",
  "FLORES ARTIFICIAIS - DEPÓSITO",
  "FLORES ARTIFICIAIS - LOJA",
  "FLORES E FLORICULTURAS - DEPÓSITO",
  "FLORES E FLORICULTURAS - LOJA",
  "FOGOS DE ARTIFICIO - DEPÓSITO",
  "FOGOS DE ARTIFICIO - LOJA",
  "FOSFOROS - LOJAS E/OU DEPOSITO",
  "FOTOGRAFO COM OU SEM REVELAÇÃO",
  "FOTOLITO",
  "FRIGORIFICOS - CAMARAS DE REFRIGERACAO",
  "FRUTAS, HORTI FRUTI -DEPÓSITO",
  "FRUTAS, HORTI FRUTI -LOJA",
  "FUMOS, CHARUTOS E CIGARROS - DEPÓSITO",
  "FUMOS, CHARUTOS E CIGARROS - LOJA",
  "FUNEBRES, ARTIGOS - LOJA E/OU DEPOSITO",
  "GARAGENS - COM DEP. DE INFLAMAVEL",
  "GARAGENS - SEM DEP. DE INFLAMAVEL",
  "GAS CARBONICO - FABRICA",
  "GASES COMBUSTIVEIS, INCLUSIVE GLP - LOJA E/OU DEPÓSITO",
  "GELO - LOJA E/OU DEPOSITOS",
  "GRÃOS EM GERAL - COM DEFENSIVOS AGRICOLAS - DEPÓSITO",
  "GRÃOS EM GERAL - COM DEFENSIVOS AGRICOLAS - LOJA",
  "GRÃOS EM GERAL - SEM DEFENSIVOS AGRICOLAS - DEPÓSITO",
  "GRÃOS EM GERAL - SEM DEFENSIVOS AGRICOLAS - LOJA",
  "GUARDA - MOVEIS",
  "HANGAR - COM DEP. DE INFLAMAVEL",
  "HANGAR - SEM DEP. DE INFLAMAVEL",
  "HIDROGENIO - LOJA E/OU DEPOSITO",
  "HIDROTERAPICOS, ESTABELECIMENTO",
  "HIPERMERCADOS",
  "HOSPITAIS, CLINICAS E CASAS SAUDE",
  "HOSPITALARES - DEPÓSITO",
  "HOSPITALARES - LOJA",
  "HOTEIS, POUSADAS E FLATS",
  "IGREJAS, CASAS DE CULTO E MACONARIA",
  "IMUNIZADORES - COM EMPREGO DE INFLAMAVEIS",
  "INCINERADORES - ESTAÇÃO DE TRATAMENTO DE RESIDUOS",
  "INFLAMAVEIS - DEPOSITO",
  "INFORMATICA - DEPÓSITO",
  "INFORMATICA - LOJA",
  "INFORMATICA - OFICINA",
  "INSTITUIÇÕES FINANCEIRAS",
  "INSTITUTO DE BELEZA",
  "INSTRUMENTO CIENTIFICO - DEPÓSITO",
  "INSTRUMENTO CIENTIFICO - LOJA",
  "INSTRUMENTO PRECISÃO - DEPÓSITO",
  "INSTRUMENTO PRECISÃO - LOJA",
  "INTERNET - CAFÉ",
  "JET-SKY",
  "JOALHERIAS - LOJAS OU DEPOSITOS",
  "JOALHERIAS E RELOJOARIAS - FABRICA",
  "JOGO - SALÃO DE",
  "JORNAIS E REVISTAS - BANCAS",
  "LABORATORIOS DE PESQUISAS E ANALISES",
  "LADRILHOS, PISOS E AZULEJOS - DEPOSITOS",
  "LADRILHOS, PISOS E AZULEJOS - LOJAS",
  "LANCHONETE",
  "LATICINIOS - DEPÓSITO",
  "LATICINIOS - LOJA",
  "LAVANDERIAS DE ROUPAS E TECIDOS",
  "LENHA - DEPÓSITO",
  "LENHA - LOJAS",
  "LIMPESA, MATERIAL - LOJA",
  "LIMPEZA, MATERIAL - DEPÓSITO",
  "LINGERIE, ESPARTILHOS - DEPÓSITO",
  "LINGERIE, ESPARTILHOS - LOJA",
  "LINHA, LÃ, FIOS TEXTEIS - DEPÓSITOS",
  "LINHA, LÃ, FIOS TEXTEIS - LOJA",
  "LIVRARIA, JORNAIS E REVISTAS",
  "LOCADORA DE FITAS (K7,VHS,GAME, DVD E OUTROS SIMILARES)",
  "LOJA DE DEPARTAMENTOS",
  "LOJAS DE GALERIA",
  "LOJAS EM SHOPPING",
  "LONA - ARTIGOS - DEPÓSITO",
  "LONA - ARTIGOS - LOJA",
  "LOTERICA",
  "LOUÇAS, CERÂMICAS E PORCELANAS - DEPÓSITO",
  "LOUÇAS, CERÂMICAS E PORCELANAS - LOJA",
  "MADEIRA - ARTIGOS - DEPÓSITO",
  "MADEIRA - ARTIGOS - LOJA",
  "MALAS - DEPÓSITO",
  "MALAS - LOJA",
  "MALTARIA",
  "MÁQUINA, GRANDE - DEPÓSITO",
  "MÁQUINA, GRANDE - LOJA",
  "MÁQUINA, LEVE/ESCRITORIO - DEPÓSITO",
  "MÁQUINA, LEVE/ESCRITORIO - LOJA",
  "MÁQUINA, OPERATRIZES - DEPÓSITO",
  "MÁQUINA, OPERATRIZES - LOJA",
  "MÁQUINA, PEQUENA E MÉDIA - DEPÓSITO",
  "MÁQUINA, PEQUENA E MÉDIA - LOJA",
  "MARINA",
  "MARMORARIAS, PEDRAS DE REVESTIMENTO E CANTARIA",
  "MASSAS ALIMENTICIAS - DEPÓSITO",
  "MASSAS ALIMENTICIAS - LOJA",
  "MATERIAIS ELÉTRICOS E ILUMINAÇÃO - LOJA E/OU DEPOSITO",
  "MATERIAIS PARA CONSTRUÇÃO - LOJA E/OU DEPOSITO",
  "MEIAS - DEPÓSITOS",
  "MEIAS - LOJAS",
  "MERCADOS PUBLICOS",
  "METAL - DEPÓSITO",
  "METAL - LOJA",
  "MOLDURAS - DEPÓSITO",
  "MOLDURAS - LOJA",
  "MOTEL",
  "MOVEIS - DEPÓSITO - SEM COLCHÕES",
  "MOVEIS - LOJA - SEM COLCHOES",
  "MOVEIS - LOJA E/OU DEPOSITO - COM COLCHOES",
  "MOVEIS - LOJA E/OU DEPOSITO - SEM COLCHOES",
  "MULT-LET - DEPÓSITO",
  "MULT-LET - LOJA",
  "MUSEU",
  "MUSICA - INSTRUMENTOS MUSICAIS - LOJA E/OU DEPÓSITO",
  "NUMISMÁTICA",
  "OFICINA DE MANUTENÇÃO GERAL",
  "OLEOS LUBRIFICANTES - DEPÓSITO",
  "OLEOS LUBRIFICANTES - LOJA",
  "OLEOS VEGETAIS COMESTIVEIS - DEPÓSITO",
  "OLEOS VEGETAIS COMESTIVEIS - LOJA",
  "ORTOPEDICOS - ARTIGOS - DEPÓSITOS",
  "ORTOPEDICOS - ARTIGOS - LOJAS",
  "OTICAS - LOJA E/OU DEPOSITO",
  "OXIGENIO - LOJA E/OU DEPOSITO",
  "PADARIAS, CONFEITARIAS E PANIFICADORAS",
  "PALITOS",
  "PAPEL - BOBINA / FARDOS / RESMA - DEPOSITO",
  "PAPEL E PAPELÃO, ARTIGOS - DEPÓSITO",
  "PAPEL E PAPELÃO, ARTIGOS - LOJA",
  "PAPEL/PAPELÃO - C/ DEPOSITO APARAS",
  "PAPELARIA, LOJA E/OU DEPOSITOS",
  "PARQUE DE DIVERSÃO OU TEMÁTICO",
  "PEDRAS PRECIOSAS E SEMI PRECIOSAS - LOJA E/OU DEPÓSITO",
  "PEIXARIA",
  "PEIXES - SALGAS",
  "PENHORES (CASAS)",
  "PENSÃO",
  "PERFUMARIA DEPÓSITO",
  "PERFUMARIA LOJA",
  "PET-SHOP",
  "PINTURAS - FAIXAS",
  "PINTURAS - OFICINAS",
  "PIRETRO (FLOR DE)",
  "PIZZARIA",
  "PLANTAÇÕES",
  "PLASTICO, ARTIGOS - DEPÓSITO (EXCETO RECICLAGEM)",
  "PLASTICO, ARTIGOS - LOJA (EXCETO RECICLAGEM)",
  "PLUMAS - LOJA E/OU DEPÓSITO",
  "PNEUS E CAMARA DE AR - LOJA E DEPOSITO",
  "PNEUS E CAMARA DE AR - OFICINA",
  "PORTO",
  "POSTOS DE SERVIÇO E LUBRIFICAÇÃO - COM VENDA DE COMBUSTIVEL",
  "POSTOS DE SERVIÇO E LUBRIFICAÇÃO - SEM VENDA DE COMBUSTIVEL",
  "PRODUTOS ALIMENTICIOS - DEPÓSITO",
  "PRODUTOS ALIMENTICIOS - LOJA",
  "PRODUTOS DE LIMPEZA - DEPÓSITO",
  "PRODUTOS DE LIMPEZA - LOJA",
  "PRODUTOS FARMACEUTICOS, COM INFLAMAVEL - DEPÓSITO",
  "PRODUTOS FARMACEUTICOS, COM INFLAMAVEL - LOJA",
  "PRODUTOS FARMACEUTICOS, SEM INFLAMAVEL - DEPÓSITO",
  "PRODUTOS FARMACEUTICOS, SEM INFLAMAVEL - LOJA",
  "PRODUTOS QUIMICOS - COM INFLAMAVEL - DEPÓSITO",
  "PRODUTOS QUIMICOS - COM INFLAMAVEL - LOJA",
  "PRODUTOS QUIMICOS - SEM INFLAMAVEL - DEPÓSITO",
  "PRODUTOS QUIMICOS - SEM INFLAMAVEL - LOJA",
  "PROTESE DENTÁRIA - OFICINA",
  "PROTESE, OFICINA - VIDE MATERIAL EMPREGADO",
  "QUARTEL - DELEGACIAS E TRANSPORTADORAS DE VALORES COM ARMAS E MUNIÇÕES",
  "QUITANDAS",
  "RAÇÃO - DEPOSITO",
  "RADIO EMISSORA",
  "RADIO TORRES DE TRANSMISSÃO",
  "RADIOLOGIA, CLINICAS E CONSULTÓRIOS",
  "RELIGIOSO, ARTIGO - DEPÓSITO",
  "RELIGIOSO, ARTIGO - LOJA",
  "RELOJOARIA - DEPÓSITO",
  "RELOJOARIA - LOJA",
  "REMEDIOS (DEPOSITO)",
  "RESTAURANTE",
  "ROTISSERIE",
  "ROUPAS E MALHAS - DEPÓSITO",
  "ROUPAS E MALHAS - LOJA",
  "SABÃO, SABONETE E SAPONACEOS - DEPÓSITO",
  "SABÃO, SABONETE E SAPONACEOS - LOJA",
  "SACOS DE FIBRAS VEGETAIS - DEPOSITOS, COSTURA OU CONSERTO DE SACOS",
  "SAL - DEPOSITOS",
  "SALÕES DE BAILE",
  "SANITARIOS - ARTIGOS - DEPÓSITO",
  "SANITARIOS - ARTIGOS - LOJA",
  "SAUNA",
  "SECOS E MOLHADOS - DEPÓSITO",
  "SECOS E MOLHADOS - LOJAS",
  "SHOPPING CENTER",
  "SHOPPING CENTER (AREAS COMUNS) - QUIOSQUES DE VENDA",
  "SOJA - DEPOSITO DE GRÃOS A GRANEL",
  "SOJA - DEPOSITO DE SEMENTES",
  "SOJA - DEPOSITO DEMAIS RISCOS",
  "SORVETERIA - DEPÓSITO",
  "SORVETERIA - LOJA",
  "SUPERMERCADO/HIPERMERCADO",
  "TABACARIA",
  "TAPETES - DEPOSITO",
  "TAPETES - LOJAS",
  "TECIDOS - DEPÓSITO",
  "TECIDOS - LOJA",
  "TELEFÉRICO",
  "TELEFONE - DEPÓSITO",
  "TELEFONE - LOJA",
  "TELEVISÃO - DEPÓSITO",
  "TELEVISÃO - EMISSORA",
  "TELEVISÃO - LOJA",
  "TEMPLO",
  "TINTAS E VERNIZES - DEPÓSITO",
  "TINTAS E VERNIZES - LOJA",
  "TINTURARIA DE ROUPAS E TECIDOS",
  "TOUCADOR - DEPOSITO",
  "TOUCADOR - LOJAS",
  "TRANSPORTADORA COM INFLAMÁVEIS E ALGODÃO",
  "TRANSPORTADORA SEM INFLAMÁVEIS E ALGODÃO",
  "VELA, LOJA E/OU DEPOSITO",
  "VELÓRIO",
  "VIDEO LOCADORA",
  "VIDROS, ARTIGOS -DEPÓSITO",
  "VIDROS, ARTIGOS -LOJA",
  "VIME - JUNCO - PIAÇABA E SIMILARES - DEPÓSITO",
  "VIME - JUNCO - PIAÇABA E SIMILARES - LOJA",
  "VINHOS - DEPOSITOS",
  "VINHOS - LOJAS",
];

// CORREÇÃO: Adiciona a exportação das listas de protecionais e coberturas

export const PROTECTION_ITEMS = [
    { key: "alarmeIncendio", label: "Alarme de incêndio e/ou Detectores de fumaça" },
    { key: "alarmeInfravermelho", label: "Alarme infravermelho ou de impacto" },
    { key: "brigadaEmergencia", label: "Brigada e plano de emergência" },
    { key: "cftv", label: "CFTV - CIRCUITO FECHADO DE TV" },
    { key: "concertina", label: "Concertina e/ou cerca elétrica" },
    { key: "diqueContencao", label: "Dique ou Bacia de contenção para Inflamáveis ou produtos químicos" },
    { key: "eclusa", label: "Eclusa para pedestres e automóveis - duas barreiras de acesso" },
    { key: "extintores", label: "Extintores", required: true },
    { key: "guaritaBlindada", label: "Guarita blindada" },
    { key: "mergulhao", label: "Mergulhão" },
    { key: "outrasProtecoes", label: "Outras proteções adicionais" },
    { key: "paraRaios", label: "Para raios" },
    { key: "redeHidrantes20", label: "Rede de hidrantes com RTI de 20m³ até 60m³", hasRTI: true },
    { key: "redeHidrantes60", label: "Rede de hidrantes com RTI de 60m³ até 120m³", hasRTI: true },
    { key: "redeHidrantes120", label: "Rede de hidrantes com RTI de mais de 120m³", hasRTI: true },
    { key: "redeSprinklers", label: "Rede de sprinklers" },
    { key: "sistemaGarra", label: "Sistema garra de tigre - sistema de desacelerador" },
    { key: "vigilanciaArmada", label: "Vigilância 24 h armada" },
    { key: "vigilanciaDesarmada", label: "Vigilância 24 h desarmada" },
];

export const COBERTURA_ITEMS = [
    { coberturaKey: "cobertura_0", name: "Incêndio (Inclusive decorrente de tumulto), queda de raio, explosão e implosão de qualquer natureza e queda de aeronaves", needsPeriod: false, periodoKey: "periodo_0" },
    { coberturaKey: "cobertura_1", name: "Alagamento e/ou Inundação", needsPeriod: false, periodoKey: "periodo_1" },
    { coberturaKey: "cobertura_2", name: "Anúncios / Letreiros Luminosos", needsPeriod: false, periodoKey: "periodo_2" },
    { coberturaKey: "cobertura_3", name: "Concessionária de Veiculos", needsPeriod: false, periodoKey: "periodo_3" },
    { coberturaKey: "cobertura_4", name: "Danos Elétricos", needsPeriod: false, periodoKey: "periodo_4" },
    { coberturaKey: "cobertura_5", name: "Danos Fabricação (Work Damage)", needsPeriod: false, periodoKey: "periodo_5" },
    { coberturaKey: "cobertura_6", name: "Derrame ou Vazamento de Chuveiros Automáticos (Sprinklers) e Rede de Hidrante", needsPeriod: false, periodoKey: "periodo_6" },
    { coberturaKey: "cobertura_7", name: "Desmoronamento", needsPeriod: false, periodoKey: "periodo_7" },
    { coberturaKey: "cobertura_8", name: "Despesas com Honorários de Peritos – Danos Materiais", needsPeriod: false, periodoKey: "periodo_8" },
    { coberturaKey: "cobertura_9", name: "Despesas de Salvamento e Contenção de Sinistros", needsPeriod: false, periodoKey: "periodo_9" },
    { coberturaKey: "cobertura_10", name: "Despesas Extraordinarias", needsPeriod: false, periodoKey: "periodo_10" },
    { coberturaKey: "cobertura_11", name: "Deterioração de Mercadorias em Ambientes Frigorificados", needsPeriod: false, periodoKey: "periodo_11" },
    { coberturaKey: "cobertura_12", name: "Equipamentos Arrendados e/ou Cedidos a Terceiros", needsPeriod: false, periodoKey: "periodo_12" },
    { coberturaKey: "cobertura_13", name: "Equipamentos Cine/Foto/TV Operados em Estúdios, Laboratórios ou Reportagens Externas", needsPeriod: false, periodoKey: "periodo_13" },
    { coberturaKey: "cobertura_14", name: "Equipamentos Cine/Foto/TV Operados em Estúdios, Laboratórios ou Reportagens Internas", needsPeriod: false, periodoKey: "periodo_14" },
    { coberturaKey: "cobertura_16", name: "Equipamentos Eletrônicos COM Roubo", needsPeriod: false, periodoKey: "periodo_16" },
    { coberturaKey: "cobertura_15", name: "Equipamentos Eletrônicos SEM Roubo", needsPeriod: false, periodoKey: "periodo_15" },
    { coberturaKey: "cobertura_17", name: "Equipamentos em Exposição", needsPeriod: false, periodoKey: "periodo_17" },
    { coberturaKey: "cobertura_18", name: "Equipamentos Estacionários", needsPeriod: false, periodoKey: "periodo_18" },
    { coberturaKey: "cobertura_19", name: "Equipamentos Móveis (Com Tração Própria)", needsPeriod: false, periodoKey: "periodo_19" },
    { coberturaKey: "cobertura_20", name: "Equipamentos Portáteis", needsPeriod: false, periodoKey: "periodo_20" },
    { coberturaKey: "cobertura_21", name: "Extravasamento de Materiais em Estado de Fusão", needsPeriod: false, periodoKey: "periodo_21" },
    { coberturaKey: "cobertura_22", name: "Fermentação Própria ou Combustão Espontânea", needsPeriod: false, periodoKey: "periodo_22" },
    { coberturaKey: "cobertura_23", name: "Fidelidade", needsPeriod: false, periodoKey: "periodo_23" },
    { coberturaKey: "cobertura_24", name: "Galpão Vinilona", needsPeriod: false, periodoKey: "periodo_24" },
    { coberturaKey: "cobertura_25", name: "Incêndio Resultante de Queimadas em Zonas Rurais", needsPeriod: false, periodoKey: "periodo_25" },
    { coberturaKey: "cobertura_26", name: "Lucros Cessantes – Perda de Lucro Bruto (decorrente exclusivamente da garantia básica - Incêndio (Inclusive decorrente de tumulto), queda de raio, explosão e implosão de qualquer natureza e queda de aeronaves)", needsPeriod: true, periodoKey: "periodo_26" },
    { coberturaKey: "cobertura_55", name: "Lucros Cessantes decorrente exclusivamente de Danos Elétricos", needsPeriod: true, periodoKey: "periodo_55" },
    { coberturaKey: "cobertura_34", name: "Despesas Fixas (decorrente exclusivamente da garantia básica - Incêndio (Inclusive dec de tumulto), queda de raio, explosão e implosão de qualquer natureza e queda de aeronaves)", needsPeriod: true, periodoKey: "periodo_34" },
    { coberturaKey: "cobertura_35", name: "Despesas Fixas decorrente de Danos Elétricos", needsPeriod: true, periodoKey: "periodo_35" },
    { coberturaKey: "cobertura_36", name: "Despesas Fixas decorrente de Vendaval, Furacão, Ciclone, Tornado, Granizo, Impacto de Veículos Terrestres e Fumaça", needsPeriod: true, periodoKey: "periodo_36" },
    { coberturaKey: "cobertura_27", name: "Movimentação Interna de Mercadorias", needsPeriod: false, periodoKey: "periodo_27" },
    { coberturaKey: "cobertura_56", name: "Pagamento de Aluguel a Terceiros para Equipamentos", needsPeriod: false, periodoKey: "periodo_56" },
    { coberturaKey: "cobertura_28", name: "Pequenas Obras de Engenharia, para Ampliações, Reparos ou Reformas", needsPeriod: false, periodoKey: "periodo_28" },
    { coberturaKey: "cobertura_29", name: "Perda e/ou Pagamento de Aluguel", needsPeriod: true, periodoKey: "periodo_29" },
    { coberturaKey: "cobertura_30", name: "Quebra de Maquinas", needsPeriod: false, periodoKey: "periodo_30" },
    { coberturaKey: "cobertura_31", name: "Quebra de Vidros", needsPeriod: false, periodoKey: "periodo_31" },
    { coberturaKey: "cobertura_32", name: "Recomposição de Registros e Documentos", needsPeriod: false, periodoKey: "periodo_32" },
    { coberturaKey: "cobertura_33", name: "Remoção de Entulhos", needsPeriod: false, periodoKey: "periodo_33" },
    { coberturaKey: "cobertura_37", name: "Responsabilidade Civil - Chapa de Experiência - Danos ao Veículo", needsPeriod: false, periodoKey: "periodo_37" },
    { coberturaKey: "cobertura_38", name: "Responsabilidade Civil - Chapa de Experiência - Danos a veículos de terceiros e Danos Materiais ou Corporais a Terceiros", needsPeriod: false, periodoKey: "periodo_38" },
    { coberturaKey: "cobertura_39", name: "Responsabilidade Civil - Operações", needsPeriod: false, periodoKey: "periodo_39" },
    { coberturaKey: "cobertura_40", name: "Responsabilidade Civil – Dano Morais", needsPeriod: false, periodoKey: "periodo_40" },
    { coberturaKey: "cobertura_41", name: "Responsabilidade Civil – Empregador", needsPeriod: false, periodoKey: "periodo_41" },
    { coberturaKey: "cobertura_42", name: "Responsabilidade Civil - Estabelecimentos de Ensino", needsPeriod: false, periodoKey: "periodo_42" },
    { coberturaKey: "cobertura_43", name: "Responsabilidade Civil - Estabelecimentos de Hospedagem e Similares", needsPeriod: false, periodoKey: "periodo_43" },
    { coberturaKey: "cobertura_44", name: "Responsabilidade Civil - Guarda de Veículos de Terceiros – R.C. Garagista (Global) – Veículo Nacional ou Importado", needsPeriod: false, periodoKey: "periodo_44" },
    { coberturaKey: "cobertura_45", name: "Responsabilidade Civil - Guarda de Veículos de Terceiros (Incêndio e Roubo) – Nacional ou Importado", needsPeriod: false, periodoKey: "periodo_45" },
    { coberturaKey: "cobertura_46", name: "Responsabilidade Civil – Cobertura para Percurso entre o local de recepção e o local de guarda dos veículos – Danos Materiais a veículos de terceiros e Danos Materiais ou Corporais a Terceiros", needsPeriod: false, periodoKey: "periodo_46" },
    { coberturaKey: "cobertura_48", name: "Responsabilidade Civil - Portões", needsPeriod: false, periodoKey: "periodo_48" },
    { coberturaKey: "cobertura_47", name: "Responsabilidade Civil – Prestação de Serviços em locais de terceiros", needsPeriod: false, periodoKey: "periodo_47" },
    { coberturaKey: "cobertura_49", name: "Roubo e Furto Qualificado de Bens nas Dependências do Segurado", needsPeriod: false, periodoKey: "periodo_49" },
    { coberturaKey: "cobertura_50", name: "Roubo de Valores no Interior das Dependências do Segurado", needsPeriod: false, periodoKey: "periodo_50" },
    { coberturaKey: "cobertura_51", name: "Roubo e Furto Qualificado de Valores em Trânsito fora do estabelecimento", needsPeriod: false, periodoKey: "periodo_51" },
    { coberturaKey: "cobertura_52", name: "Tumultos, Greves e Lock-Out", needsPeriod: false, periodoKey: "periodo_52" },
    { coberturaKey: "cobertura_53", name: "Vendaval, Furacão, Ciclone, Tornado, Granizo, Impacto de Veículos Terrestres e Fumaça", needsPeriod: false, periodoKey: "periodo_53" },
    { coberturaKey: "cobertura_54", name: "Vazamento Acidental de Tanque, Ruptura de Encanamentos ou Tubulações do Próprio Imóvel", needsPeriod: false, periodoKey: "periodo_54" },
    { coberturaKey: "cobertura_57", name: "Despesas com instalação em novo local", needsPeriod: false, periodoKey: "periodo_57" },
    { coberturaKey: "cobertura_58", name: "Carga, Descarga, Içamento e Descida de Bens Segurados", needsPeriod: false, periodoKey: "periodo_58" },
    { coberturaKey: "cobertura_59", name: "Roubo ou Furto Qualificado de Bens de Hospedes", needsPeriod: false, periodoKey: "periodo_59" },
    { coberturaKey: "cobertura_60", name: "Despesa com defesa em juízo", needsPeriod: false, periodoKey: "periodo_60" },
    { coberturaKey: "cobertura_61", name: "Responsabilidade Civil - Riscos Contingentes de Veículos", needsPeriod: false, periodoKey: "periodo_61" },
];


export const SITUACAO_SEGURO_OPTIONS = [
    { value: "seguro-novo", label: "Seguro Novo" },
    { value: "1a-renovacao-asas", label: "1ª Renovação ASAS" },
    { value: "2a-renovacao-asas", label: "2ª Renovação ASAS" },
    { value: "3a-renovacao-asas", label: "3ª Renovação ASAS" },
    { value: "4a-renovacao-asas", label: "4ª Renovação ASAS" },
    { value: "renovacao-outra-cia", label: "Renovação outra Cia" },
];

export const SITUACAO_SINISTRO_OPTIONS = [
    { value: "renovacao-com-sinistro", label: "Renovação com sinistro" },
    { value: "sem-sinistros-1-ano", label: "Sem sinistros em todos os locais de risco há 1 ano de renovação" },
    { value: "sem-sinistros-2-anos", label: "Sem sinistros em todos os locais de risco há 2 anos de renovação" },
    { value: "sem-sinistros-3-anos", label: "Sem sinistros em todos os locais de risco há 3 anos de renovação" },
    { value: "sem-sinistros-4-anos", label: "Sem sinistros em todos os locais de risco há 4 anos de renovação" },
    { value: "sem-sinistros-5-anos", label: "Sem sinistros em todos os locais de risco há 5 anos de renovação" },
];

export const CLASSE_CONSTRUCAO_OPTIONS = [
    { value: "superior", label: "Superior" },
    { value: "solida", label: "Sólida" },
    { value: "mista", label: "Mista" },
    { value: "inferior", label: "Inferior" },
    { value: "isopainel-25", label: "Isopainel com até 25% da área" },
    { value: "isopainel-mais-25", label: "Isopainel com mais de 25% da área" },
];

export const QUESTOES_ADICIONAIS_SEGURO = [
    { key: "clausulaBeneficiaria", label: "Será necessária a inclusão de cláusula beneficiária?", placeholder: "Ex.: Sim - Banco XPTO S.A." },
    { key: "sinistralidade5Anos", label: "Sinistralidade dos últimos 5 anos:", placeholder: "Ex.: Nenhum sinistro registrado" },
    { key: "possuiuSeguroAnterior", label: "Possuiu seguro anteriormente?", placeholder: "Ex.: Sim, até 03/2025 na Seguradora XPTO" },
    { key: "motivoSemSeguro", label: "Informar o motivo do mesmo estar sem seguro até a presente data:", placeholder: "Ex.: Apólice vencida e não renovada" },
    { key: "localEmOperacao", label: "O local está em operação/atividade?", placeholder: "Ex.: Sim, em operação normal" },
    { key: "condominioLogistico", label: "Local fica dentro de condomínio logístico/empresarial e se divide o prédio com outras empresas?", placeholder: "Ex.: Sim, condomínio logístico, prédio dividido com 3 empresas" },
] as const;

// Limite total dos anexos da Etapa 8. Em produção (Vercel) o corpo da requisição
// é limitado a ~4,5 MB, por isso o padrão conservador.
export const MAX_UPLOAD_MB = Number(process.env.NEXT_PUBLIC_MAX_UPLOAD_MB || 4);

export const TIPOS_ANEXO_ACEITOS =
    ".pdf,.jpg,.jpeg,.png,.webp,.heic,.doc,.docx,.xls,.xlsx,.csv,.txt";
